In [9]:
"""
Create a 2X6 array by giving input from keyboard (can be +ve,-ve or 0)
A) find the row wise and column wise sum
B) find the number of zeroes, number of odd int and number of even ints
C) change all -ve numbers to 999
D) Count and calculate the number of duplicates(if it exists) and display it
D) Reshape the array into a 3X 4 array 
"""
import numpy as np
def question():
    print("Please enter exactly 12 integers")
    userInput = input()
    elements = list(map(int,userInput.split()))
    if len(elements)!= 12 :
        print("Enter exactly 12 integers please: ")
        return
    arr = np.array(elements).reshape(2,6)
    print(f"{arr}")
    rowSum = np.sum(arr,axis=1)
    colSum = np.sum(arr,axis=0)
    numZero = np.sum(arr == 0)
    numOdd = np.sum(arr%2 != 0)
    numEven = np.sum(arr%2 == 0)
    arrPos = np.where(arr < 0,999,arr)
    dupFree,counts = np.unique(arrPos,return_counts = True)
    duplicates = dupFree[counts>1]
    duplicatesCount = counts[counts>1]
    print(f"Sum of Rows:{rowSum}, Sum of Columns:{colSum},\nNumber of zeroes:{numZero},\nNumber of Odd numbers:{numOdd}, \nNumber of Even Numbers:{numEven}, \nNew Array: {arrPos}, \n Duplicates and their count: {duplicates},{duplicatesCount}")
    reshapedArr = arrPos.reshape(3, 4)
    print(f"\nReshaped 3x4 Array:\n{reshapedArr}")
question()

Please enter exactly 12 integers
1 2 3 4 4 3 2 1 -5 4 3 2
[[ 1  2  3  4  4  3]
 [ 2  1 -5  4  3  2]]
Sum of Rows:[17  7], Sum of Columns:[ 3  3 -2  8  7  5],
Number of zeroes:0,
Number of Odd numbers:6, 
Number of Even Numbers:6, 
New Array: [[  1   2   3   4   4   3]
 [  2   1 999   4   3   2]], 
 Duplicates and their count: [1 2 3 4],[2 3 3 3]

Reshaped 3x4 Array:
[[  1   2   3   4]
 [  4   3   2   1]
 [999   4   3   2]]


In [ ]:
"""
2) Theres a dataset that has to be typed as a dictionary(as part of code) consisting of 10 rows with columns titled ID, Name, Subject, Salary,Phone Number[2 entries are np.nan in this]
A) Sort the names of the faculty whose salary exceeds 50,000 in ascending order [Slightly ambiguous as it isnt mentioned that sort by names or salary wise after finding who has above 50K
B) Check how many phone numbers are Nan
C)find the mean of the salary of faculties  as per their respective subjects
D)Add another column named Bonus which is 10% of the base salary 
E) Find the number of teachers in each subject

this is a python question
you can use numpy,pandas,seaborn and matplotlib for the above questions
"""

